/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AgendaItem, NavItem, SpeakerProfile } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', icon: 'Home', href: 'home' },
  { label: 'Agenda', icon: 'Calendar', href: 'agenda' },
  { label: 'Speakers', icon: 'Users', href: 'speakers' },
  { label: 'Venue', icon: 'MapPin', href: 'venue' },
  { label: 'FAQs', icon: 'HelpCircle', href: 'faqs' },
  { label: 'Feedback', icon: 'MessageSquare', href: 'feedback' },
  { label: 'Event Photos', icon: 'Camera', href: 'event-photos' },
  { label: 'Contact', icon: 'Mail', href: 'contact' },
  { label: 'About', icon: 'Info', href: 'about' },
];

export const AGENDA_DATA: AgendaItem[] = [
  {
    id: '1',
    day: 1,
    time: '07:00 - 08:15',
    title: 'Arrival, Registration & Breakfast',
    location: 'Registration Desk / Foyer',
    description: 'Arrival, registration, and breakfast for delegates from government, private sector investors, lenders, developers, and advisors.',
    type: 'networking',
  },
  {
    id: '2',
    day: 1,
    time: '08:15 - 09:00',
    title: 'Opening Remarks & Keynote Address',
    speaker: 'Hon. John Mbadi and Opening Dignitaries',
    location: 'Main Ballroom',
    description: 'Prayers, National/EAC Anthem, and opening remarks by Eng. Kefa Seda, John Mwendwa, Wangari Muikia, Muneer Ferozie, Dr. Chris Kiptoo, and Cyrell Wagunda. Keynote by Hon. John Mbadi, Cabinet Secretary for the National Treasury.',
    type: 'keynote',
  },
  {
    id: '3',
    day: 1,
    time: '09:00 - 10:15',
    title: 'PPP Priorities Presentation',
    speaker: 'PPPD',
    location: 'Main Ballroom',
    description: 'Presentation on Kenya PPP priorities, pipeline overview, strategic sectors, implementation priorities, and live audience Q&A.',
    type: 'keynote',
  },
  {
    id: '4',
    day: 1,
    time: '10:15 - 11:15',
    title: 'Panel 1: Commercial Attractiveness',
    speaker: 'Moderator: Muneer Ferozie (IFC)',
    location: 'Main Ballroom',
    description: 'Commercial attractiveness and structuring PPPs to attract credible bidders, including viability, risk allocation, land and permitting, FX/payment risk, procurement credibility, and pipeline visibility. Panelists: Rahim Virani, Allan Munyua, Marie-Laure Mazaud, Andrew Muigai, Dr. Kenneth Namunje.',
    type: 'workshop',
  },
  {
    id: '5',
    day: 1,
    time: '11:15 - 11:30',
    title: 'Health Break',
    location: 'Foyer',
    description: 'Short transition and networking break.',
    type: 'break',
  },
  {
    id: '6',
    day: 1,
    time: '11:30 - 12:45',
    title: 'Panel 2: Bankability & Credit Enhancement',
    speaker: 'Moderator: Nathan Rono Tuimising (World Bank Group)',
    location: 'Main Ballroom',
    description: 'Bankability from the private sector perspective: guarantees, political risk mitigation, blended finance, insurance, and government credit enhancement tools to build lender confidence. Panelists: Susan Njuguna, Reginald Max, Jessica Erickson, Prof. Albert Mumma, Jasper Onyango, Obbie Banda.',
    type: 'workshop',
  },
  {
    id: '7',
    day: 1,
    time: '12:45 - 14:00',
    title: 'Lunch and Networking',
    location: 'Dining Area',
    description: 'Lunch break and stakeholder networking across public institutions, private investors, and development partners.',
    type: 'networking',
  },
  {
    id: '8',
    day: 1,
    time: '14:00 - 15:30',
    title: 'Panel 3: From Policy to Projects',
    speaker: 'Moderator: Christine Nganga (PPPD)',
    location: 'Main Ballroom',
    description: 'Policy makers and private sector discuss solutions to financial close barriers, including regulatory bottlenecks, fiscal and tax issues, legal structuring, approvals/permitting, and execution challenges in energy and water. Panelists: Risper Simiyu, Sharon Irungu, Dr. John Mutua, Willy Ireri, Richard Cheruiyot, Beatrice Nyabira.',
    type: 'workshop',
  },
  {
    id: '9',
    day: 1,
    time: '15:30 - 15:45',
    title: 'Call to Action Session',
    speaker: 'Eng. Kefa Seda and Alexandre Leigh',
    location: 'Main Ballroom',
    description: 'Closing strategic call to action focused on credible investment, execution readiness, and next-step engagement across institutions and sponsors.',
    type: 'keynote',
  },
  {
    id: '10',
    day: 1,
    time: '15:45 - 16:00',
    title: 'Health Break',
    location: 'Foyer',
    description: 'Final transition break.',
    type: 'break',
  },
  {
    id: '11',
    day: 1,
    time: '16:00',
    title: 'End of Symposium',
    location: 'Main Ballroom',
    description: 'Formal end of symposium proceedings.',
    type: 'break',
  },
];

export const EVENT_INFO = {
  title: 'Kenya Private Sector Focused PPP Symposium',
  tagline: 'Private Sector Focused PPP Symposium',
  date: 'May 12, 2026',
  location: 'Villa Rosa Kempinski, Nairobi',
  description: 'An executive-level forum convened by the National Treasury PPP Directorate with support from the World Bank and IFC to strengthen confidence in Kenya\'s PPP pipeline, improve bankability dialogue, and advance credible private sector participation in infrastructure delivery.',
  bannerImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop',
};

export const SPEAKERS_DATA: SpeakerProfile[] = [
  {
    id: 'mbithe-muema',
    name: 'Mbithe Muema',
    title: 'Head of Training, CPF Training & Consulting',
    role: 'Event MC',
    session: 'Opening Session and Programme Flow',
    time: '08:15 - 16:00',
    image: '/speakers/Mbithe Muema.jpg',
    bio: 'Mbithe Muema leads programme moderation and delegates session flow, ensuring the symposium remains focused, timely, and commercially relevant for public and private stakeholders.',
  },
  {
    id: 'muneer-ferozie',
    name: 'Muneer Ferozie',
    title: 'Regional Manager and Head of Transaction Advisory PPPs and Corporate Finance Africa Region, IFC',
    role: 'Panel 1 Moderator',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Muneer Ferozie.jpg',
    bio: 'Muneer provides an investor-facing transaction advisory lens on how project structuring, procurement credibility, and risk allocation shape bankable infrastructure opportunities in Africa.',
  },
  {
    id: 'rahim-virani',
    name: 'Rahim Virani',
    title: 'Senior Investment Officer, Infrastructure, IFC',
    role: 'Panel 1 Panelist',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Rahim Virani.jpg',
    bio: 'Rahim shares IFC infrastructure investment perspectives on sponsor quality, transaction readiness, and the commercial parameters that drive successful project close.',
  },
  {
    id: 'allan-munyua',
    name: 'Allan Munyua',
    title: 'Infrastructure Development and Investment Expert',
    role: 'Panel 1 Panelist',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Allan Munyua .jpg',
    bio: 'Allan contributes practical structuring insights on investor appetite, procurement credibility, and how to strengthen the project pipeline for scalable private participation.',
  },
  {
    id: 'marie-laure-mazaud',
    name: 'Marie-Laure Mazaud',
    title: 'CEO, STOA Infra and Energy',
    role: 'Panel 1 Panelist',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Marie-Laure Mazaud.jpg',
    bio: 'Marie-Laure brings an equity investor perspective on long-term infrastructure value, risk-return balance, and conditions needed for credible institutional capital deployment.',
  },
  {
    id: 'andrew-muigai',
    name: 'Andrew Muigai',
    title: 'Managing Partner, Sabaki / Utilities Partners One LLP',
    role: 'Panel 1 Panelist',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Andrew Muigai .jpg',
    bio: 'Andrew provides a local developer and operator perspective on implementation realities, permitting timelines, and risk areas that influence bidder confidence.',
  },
  {
    id: 'kenneth-namunje',
    name: 'Dr Kenneth Namunje',
    title: 'Chairman and Director, Kipeto Wind',
    role: 'Panel 1 Panelist',
    session: 'Panel 1: Commercial Attractiveness and Structuring PPPs to Attract Credible Bidders',
    time: '10:15 - 11:15',
    image: '/speakers/Dr Kenneth Namunje .jpg',
    bio: 'Dr Namunje contributes renewable IPP operating experience, highlighting execution realities from project development through financing and operational delivery.',
  },
  {
    id: 'nathan-rono-tuimising',
    name: 'Nathan Rono Tuimising, PhD',
    title: 'Senior Specialist, Public Private Partnerships, Infrastructure Finance and PPP Advisory Global Practice, World Bank Group',
    role: 'Panel 2 Moderator',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Nathan Rono Tuimising.jpg',
    bio: 'Nathan moderates dialogue on bankability, government support design, and how policy and transaction frameworks can strengthen lender confidence in PPP projects.',
  },
  {
    id: 'susan-njuguna',
    name: 'Susan Njuguna',
    title: 'Sector Head Financial Institutions Group, Stanbic Bank Kenya Ltd.',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Susan Njuguna.jpg',
    bio: 'Susan offers a commercial bank view on credit quality, sponsor strength, and practical terms required for bankable PPP transactions.',
  },
  {
    id: 'reginald-max',
    name: 'Reginald Max',
    title: 'Senior Advisor, Infrastructure and PPPs, TDB',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Reginald Max.jpg',
    bio: 'Reginald shares development finance perspectives on transaction preparation, de-risking structures, and blended approaches for regional infrastructure investments.',
  },
  {
    id: 'jessica-erickson',
    name: 'Jessica Erickson',
    title: 'Lead Infrastructure Specialist, MIGA',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Jessica Stiefler.jpg',
    bio: 'Jessica contributes political risk mitigation and guarantee perspectives to help strengthen private sector confidence in cross-border and long-tenor projects.',
  },
  {
    id: 'albert-mumma',
    name: 'Professor Albert Mumma',
    title: 'Founder and Senior Partner, Mumma & Co Advocates',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Prof. Albert Mumma.jpg',
    bio: 'Professor Mumma provides legal and policy structuring insights that support credible contracts, balanced risk allocation, and efficient dispute management.',
  },
  {
    id: 'jasper-onyango',
    name: 'Jasper Onyango',
    title: 'Senior Technical Assistance Manager, PIDG',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Jasper Onyango .jpg',
    bio: 'Jasper shares catalytic finance and technical assistance lessons on making early-stage projects investment-ready and financeable.',
  },
  {
    id: 'obbie-banda',
    name: 'Obbie Banda',
    title: 'Senior Underwriter, ATIDI',
    role: 'Panel 2 Panelist',
    session: 'Panel 2: What Does Bankability Mean to the Private Sector?',
    time: '11:30 - 12:45',
    image: '/speakers/Obbie Banda.jpg',
    bio: 'Obbie discusses political and credit risk cover instruments that improve financing certainty and reduce perceived downside risk for investors.',
  },
  {
    id: 'christine-nganga',
    name: 'Christine Nganga',
    title: 'Director, Public Private Partnerships Directorate, The National Treasury',
    role: 'Panel 3 Moderator',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Christine Nganga.jpg',
    bio: 'Christine leads discussion on translating policy intent into executable projects with clear approvals pathways and practical delivery accountability.',
  },
  {
    id: 'sharon-irungu',
    name: 'Sharon Irungu',
    title: 'Deputy Chief State Counsel, Office of the Attorney General',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Sharon Irungu.jpg',
    bio: 'Sharon provides public law and approvals insights relevant to reducing legal bottlenecks and improving transaction certainty.',
  },
  {
    id: 'risper-simiyu',
    name: 'Risper Simiyu',
    title: 'Tax Policy Advisor, The National Treasury & Commissioner, KRA',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Risper Simiyu.jpg',
    bio: 'Risper addresses tax and fiscal policy dimensions that influence transaction viability, cost of capital, and project affordability.',
  },
  {
    id: 'willy-ireri',
    name: 'Willy Ireri',
    title: 'Executive Director, Osprey Renewables',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Willy Ireri.jpg',
    bio: 'Willy contributes developer-side execution perspectives across permitting, structuring, and financing pathways to reach financial close.',
  },
  {
    id: 'john-mutua',
    name: 'Dr. John Mutua',
    title: 'Director, Directorate of Economic Regulation & Strategy, EPRA',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Dr. John Mutua.jpg',
    bio: 'Dr. Mutua shares regulator insights on sector rules, tariff considerations, and policy predictability needed for private investment confidence.',
  },
  {
    id: 'beatrice-nyabira',
    name: 'Beatrice Nyabira',
    title: 'Partner: Projects, Energy & Restructuring, IKM Advocates',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Beatrice Nyabira.jpg',
    bio: 'Beatrice offers project and restructuring counsel on contract design, lender alignment, and legal pathways to timely close.',
  },
  {
    id: 'angela-kimani',
    name: 'Angela Kimani',
    title: 'Ag. Director Corporate Services, Water Services Regulatory Board (WASREB)',
    role: 'Panel 3 Panelist',
    session: 'Panel 3: From Policy to Projects',
    time: '14:00 - 15:30',
    image: '/speakers/Angela Kimani.jpg',
    bio: 'Angela contributes water sector regulatory and institutional perspectives on strengthening project execution and financing confidence.',
  },
];

export const SPONSORS = [
  { name: 'IBRD', logo: '/images/ibrd-logo-png-transparent.png' },
  { name: 'ICSID', logo: '/images/icsd.png' },
  { name: 'IDA', logo: '/images/ida.jpg.jpeg' },
  { name: 'MIGA', logo: '/images/multilateral-investment.png' },
  { name: 'IFC', logo: '/images/GovernmentPPP.jpeg' },
  { name: 'ICSID Global', logo: '/images/wb.jpeg' },
];
